#!/bin/bash

# Copyright 2021 Melwyn Francis Carlo

# This may be changed as appropriate.
scilab_dir="/home/mfcarlo/Documents/Database/Software/Science\
/Mathematics/Scilab";
# This may be changed as per preference.
default_working_dir="$HOME";


working_dir=$1;

if [ -z $1 ]; then
    working_dir=$default_working_dir;
fi

# Replace '6.1.0' with the correct version number.
if [ -d "$working_dir" ]; then
    pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY \
    $scilab_dir/scilab-6.1.0/bin/scilab-cli -e \
    "chdir(\"$working_dir\"); clear; clc();"
else
    echo -e "\n\n  ERROR: The directory '$working_dir' does not exist.\n\n";
    exit 1;
fi
